### ISSUE TITLE
Enhancement - Bulk loading of data

### ISSUE THREAD

**Issue by johnp2015** [dizzib/WhoDoTheyServe.com#12]
This would be a nice feature for loading a large amount of data, perhaps from a spreadsheet.

**Comment by dizzib** [comment]
I'm afraid this is outside the scope of this project but I can offer some guidance.

I suggest a node script using a library like https://github.com/request/request to hit the wdts api at `http://localhost:4000/api`. The algorithm would be:

    login
    for each source actor
      create node
      add evidence
    for each source connection
      create edge
      add evidence

A good way to understand the api is by using developer-tools in the browser (F12) to trace the http request and response messages during manual interaction. Then replicate these calls in your script.
