### ISSUE TITLE
Run this project on windows system Is there a way

### ISSUE THREAD

**Issue by akhilsahu3** [dizzib/WhoDoTheyServe.com#14]
![image](https://cloud.githubusercontent.com/assets/16702069/12781838/ec44e3ba-ca9c-11e5-85e9-06e9f23333a8.png)

**Comment by dizzib** [comment]
1. I'm not sure this project will install let alone run under node v5.5.0. Try using https://github.com/creationix/nvm to install under node v0.10.

2. node-gyp needs python 2.7... seems you're missing it ?

Even if you could get it to install under windows certain tasks relying on Linux commands such as `pkill` will fail, so you'd need to modify the code to call the Windows equivalent.

Alternatively install it in Linux in Virtualbox or VMWare under Windows.
