### ISSUE TITLE
facing error installing on ubuntu marionette error

### ISSUE THREAD

**Issue by akhilsahu3** [dizzib/WhoDoTheyServe.com#15]
![image](https://cloud.githubusercontent.com/assets/16702069/12839609/2886165e-cc01-11e5-832c-f23c673eed99.png)

**Comment by akhilsahu3** [comment]
How to install firefox marionette

**Comment by dizzib** [comment]
Looks like it can't find a running instance of Firefox with marionette.

1. what version of Firefox is installed in Ubuntu ?

2. is Firefox up and running when you run the tests ?

You might need to supply a `-marionette` flag when you launch Firefox. I'm on Firefox 37.0.2 and need to launch it like `firefox -marionette`.

**Comment by akhilsahu3** [comment]
​Earlier it worked on same config .But i try running it again i am facing
problem installing it.​

**Comment by akhilsahu3** [comment]
Everything is latest



*T**hanks And Regards,*
*Akhil Sahu*


*PHP Trainee*
TWA Internet Technologies Pvt. Ltd.
*Email : akhil.sahu@twamail.com <akhil.sahu@twamail.com>*
*Website : www.thewebartists.com <http://www.thewebartists.com/>*

**Comment by akhilsahu3** [comment]
firefox -marionette doing so results Here image attached


![image](https://cloud.githubusercontent.com/assets/16702069/12946674/345aadfe-d01c-11e5-9169-f3751fa7b328.png)

**Comment by dizzib** [comment]
No, xvfb is only needed by Travis. Try it without xvfb.

**Comment by akhilsahu3** [comment]
then too there is cannot open display error :99

**Comment by akhilsahu3** [comment]
Reply Asap ..on this issue

![image](https://cloud.githubusercontent.com/assets/16702069/12950902/9bbd12b6-d035-11e5-868e-04c5112eab7b.png)
