### ISSUE TITLE
Is there any documentation on how to use it ?

### ISSUE THREAD

**Issue by akhilsahu3** [dizzib/WhoDoTheyServe.com#16]
I am new to ubuntu linux .No idea on how to use.I need to 
1.integrate my own data
How can i integrate my own data in json format?
I have attached screen shot of  installation.In local it asaks me to choose default map.But no maps are loaded .So how to add them
![image](https://cloud.githubusercontent.com/assets/16702069/12842142/cb6fa046-cc16-11e5-93e3-22c926a74b1d.png)

**Comment by dizzib** [comment]
By integrate do you mean import existing data ?

To add a default map, first login then select `Maps --> Create new`.

Add actors to the map as required, then set this map to be default via the 'default' checkbox (see screenshot). The default map is the map which is shown when a user first visits the site.

Finally press the blue 'Create' button to save.


![default-map](https://cloud.githubusercontent.com/assets/1223150/12843232/e3e8e410-cbef-11e5-97ba-8c02f01bbee7.png)

**Comment by akhilsahu3** [comment]
![image](https://cloud.githubusercontent.com/assets/16702069/12843462/7c58bcb4-cc1f-11e5-880c-a4ded5c42d45.png)
This is what i get as soon i open this :localhost:4000 
Now i dont need existing data in it .I need to add my own data  to be loaded as json .In which path of json should i make changes

**Comment by akhilsahu3** [comment]
As u see map is empty

**Comment by akhilsahu3** [comment]
I got it .I need to login also.Now i dont need existing data in it .I need to add my own data to be loaded as json .In which path of json should i make changes

**Comment by akhilsahu3** [comment]
As i have a lot of data which cant be added manually .I need to add a data thru a json file.hope u understand.

**Comment by dizzib** [comment]
see https://github.com/dizzib/WhoDoTheyServe.com/issues/12

**Comment by akhilsahu3** [comment]
![image](https://cloud.githubusercontent.com/assets/16702069/12971406/ddf10c6a-d0c0-11e5-956d-62917bcaa0c1.png)
This is what i get on creating new user.please reply fast asap .i created a user earlier but i forgot the password now i cant create new

**Comment by akhilsahu3** [comment]
Can the large amount of data be added directly to database in the format presented.But how is this id createdwill it work?
These unique ids are created here for each new connection node link.What  technique is use
 db.nodes.find()
{ "name" : "1republic", "meta" : { "create_user_id" : "gJcdUA_zkG", "create_date" : ISODate("2016-02-12T07:10:03.715Z") }, "_id" : "**lyoPX-tGkz**", "tags" : [  "avengers" ], "__v" : 0 }
{ "name" : "Avenger", "meta" : { "create_user_id" : "gJcdUA_zkG", "create_date" : ISODate("2016-02-12T07:11:02.479Z") }, "_id" : "**xkLhBZYzkf"**, "tags" : [  "avengers" ], "__v" : 0 }
 db.edges.find()
{ "a_node_id" : "xkLhBZYzkf", "b_node_id" : "lyoPX-tGkz", "how" : "toget", "a_is" : "eq", "when" : "2016-", "meta" : { "create_user_id" : "gJcdUA_zkG", "create_date" : ISODate("2016-02-12T07:13:07.268Z") }, "_id" : "**ekL99ZYMyz**", "__v" : 0 }
