### ISSUE TITLE
This is what i get on creating new user.please reply fast asap .i created a user earlier but i forgot the password now i cant create new

### ISSUE THREAD

**Issue by akhilsahu3** [dizzib/WhoDoTheyServe.com#18]
![image](https://cloud.githubusercontent.com/assets/16702069/12974209/17a9d812-d0d8-11e5-8110-668a9d1d4840.png)

**Comment by akhilsahu3** [comment]
{ "handle" : "zeus", "password" : "$2a$10$qe2whWJYF7vPn0BbePrkP.Zxoys1cQSO9bGZTVfb0xKdF.ApTPar2", "_id" : "x1oGEVA2C-", "__v" : 0 }
or can decrypt the password please

**Comment by dizzib** [comment]
Unfortunately there's no easy way to recover or reset the admin password. If you haven't input too much data then I suggest you delete the database and start again from scratch.

Alternatively, you could try updating the zeus password-hash to that of `userd` in the test database `wdts_test_1`:

{ "_id" : "eydxPfgMkM", "handle" : "userd", "password" : "$2a$10$I1RLRUU.FaqHQnQS3zYRsedF9oLscSiQNs2KRA3R2MX1QSZ90Cebu", "__v" : 0 }

The password should be `Pass1!`

**Comment by akhilsahu3** [comment]
Thanks for help
