### ISSUE TITLE
Integrate own data issue

### ISSUE THREAD

**Issue by akhilsahu3** [dizzib/WhoDoTheyServe.com#19]
Can the large amount of data be added directly to database in the format presented.But how is this id createdwill it work?I tried adding data manually but that doesnt seem to work.I dont know whats the issue.May be the unique id is the issue. I changed the unique keep in mind the  format of id . but that doesnt seem to help
These unique ids are created here for each new connection node link.What technique is use
db.nodes.find()
{ "name" : "1republic", "meta" : { "create_user_id" : "gJcdUA_zkG", "create_date" : ISODate("2016-02-12T07:10:03.715Z") }, "_id" : "**lyoPX-tGkz**", "tags" : [ "avengers" ], "__v" : 0 }
{ "name" : "Avenger", "meta" : { "create_user_id" : "gJcdUA_zkG", "create_date" : ISODate("2016-02-12T07:11:02.479Z") }, "_id" : "**xkLhBZYzkf**", "tags" : [ "avengers" ], "__v" : 0 }
db.edges.find()
{ "a_node_id" : "xkLhBZYzkf", "b_node_id" : "lyoPX-tGkz", "how" : "toget", "a_is" : "eq", "when" : "2016-", "meta" : { "create_user_id" : "gJcdUA_zkG", "create_date" : ISODate("2016-02-12T07:13:07.268Z") }, "_id" : "ekL99ZYMyz", "__v" : 0 }

How u added images of maps and other to your map

**Comment by dizzib** [comment]
Hmm, looks ok. Ids are generated by https://github.com/dylang/shortid in https://github.com/dizzib/WhoDoTheyServe.com/blob/dev/site/api/model/plugin-id.ls.

If you're hacking the database (i.e. bypassing the api) then you'll need to restart node after every change because the data is cached in memory.

**Comment by akhilsahu3** [comment]
Thanks

**Comment by akhilsahu3** [comment]
How do you add images of Map or other small icon images

**Comment by dizzib** [comment]
https://github.com/dizzib/WhoDoTheyServe.com/blob/dev/site/boot/hive/map.json.ls
https://github.com/dizzib/WhoDoTheyServe.com/blob/dev/site/app/view/map/graph/node.ls
