### ISSUE TITLE
Special characters in Actor  Names

### ISSUE THREAD

**Issue by johnp2015** [dizzib/WhoDoTheyServe.com#7]
Can you allow or let us know what to modify to allow some special characters in the Actor names, such as a dash or period? I tried changing the regex in validation but a DB error occurs.

Thanks

**Comment by dizzib** [comment]
You should be able to simply tweak `node.name.regex` in https://github.com/dizzib/WhoDoTheyServe.com/blob/master/site/lib/model-constraints.ls. Currently only a single dash or space can separate words as specified by `[- ]` in the regex, so names like `foo-bar` should already work.

Special regex chars such as `.` need to be escaped in https://github.com/dizzib/WhoDoTheyServe.com/blob/master/site/api/model/nodes.ls for the case-insensitive duplicate check to work against the db.

You've also uncovered a bug where `ApiError` is not bubbling correctly and therefore duplicate detections are not being reported in the browser.

**Comment by johnp2015** [comment]
I changed both model-constraints.js and app.js to the regex below and still get an error when adding a "period" to the actor name:

One or more fields have errors. Please correct them before retrying. 

I don't want to have to rebuild the project, if possible.

node: {
      name: {
        info: 'a string of 4 to 50 letters or numbers e.g. Bank of England',
        regex: /(.+)/i
      }
    },

One or more fields have errors. Please correct them before retrying.

**Comment by johnp2015** [comment]
Ignore last comment, I needed to restart the server
