### ISSUE TITLE
Map Design Mode - Dragging Actors

### ISSUE THREAD

**Issue by johnp2015** [dizzib/WhoDoTheyServe.com#8]
It appears that when I drag an Actor around the map that other actors also move. Is there anyway to lock actor positions so that they don't affect other actors?

**Comment by dizzib** [comment]
Yes, each actor on a map has a [thumb-tack icon](http://fortawesome.github.io/Font-Awesome/icon/thumb-tack/) which you can toggle to fix or free its position.

**Comment by johnp2015** [comment]
Ahhh I see, perfect, this is great!
