### ISSUE TITLE
Enhancement request - Allow multiple map tabs

### ISSUE THREAD

**Issue by johnp2015** [dizzib/WhoDoTheyServe.com#9]
It would be nice to select different diagrams and be able to have them added as tabs to easily switch between.

**Comment by dizzib** [comment]
Good idea. The navbar has limited width so the number of extra tabs shown cannot be too many, so maybe just show the last 3 or 4 selected.

**Comment by dizzib** [comment]
Due to limited space on mobile platforms I've gone with a 2-tab solution for now. Feel free to reopen if this isn't enough.
